spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ismdb
    username: ism
    password: ism
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
